### ISSUE TITLE
[Front-End]: HTML elements should stay at the bottom when resizing window

### ISSUE THREAD

**Issue by alesbe** [alesbe/sign-up-fungi-prototype#2]
## Problem
The change theme button, the "Already have an account" and the background image does not stay in place when resizing the window. Here is a comparison:

![normal](https://i.imgur.com/kYJHhm2.png)
*Without resizing*

<hr></hr>

![resized](https://i.imgur.com/uWLL7si.png)
*Resized*

<hr></hr>

## Expected behaviour
- The background image should cover the empty area at the bottom
-  The "Change theme" button should stay at the bottom right corner
- The "Already have an account? Log in" text should stay at the bottom

<hr></hr>

Happy hacktoberfest 🙌

**Comment by imanpalsingh** [comment]
Hey can i pick this up?

**Comment by alesbe** [comment]
Sure, I'll assign it!

**Comment by imanpalsingh** [comment]
Hey @alesbe  please have a look at this https://github.com/alesbe/sign-up-fungi-prototype/pull/3
